#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
mkdir -p "$HOME/.scratch"
ENV_FILE="${CUTOVER_ENV_FILE:-$HOME/.scratch/vllm-alerting-cutover.env}"

set_control() {
  local mode="$1"
  printf '%s\n' "$mode" | aws s3 cp - "s3://${CONTROL_BUCKET}/control/${ALERT_PATH}.mode" --only-show-errors
}

banner "vLLM alerting cutover or rollback"

stage "Choose operation and path"
say "Configuration is public metadata. DATABASE_URL stays in your environment."
ask ACTION "Operation (cutover or rollback):"
ask ALERT_PATH "Alert path (fast_ci or full_ci):"
ask CONTROL_BUCKET "S3 checkpoint/control bucket name:"
ask OLD_HOST "Old automation SSH target (for example ubuntu@dev):"
[[ "$ACTION" == "cutover" || "$ACTION" == "rollback" ]] || { warn "operation must be cutover or rollback"; exit 2; }
[[ "$ALERT_PATH" == "fast_ci" || "$ALERT_PATH" == "full_ci" ]] || { warn "path must be fast_ci or full_ci"; exit 2; }
[[ "$CONTROL_BUCKET" =~ ^[a-z0-9][a-z0-9.-]+$ ]] || { warn "invalid S3 bucket name"; exit 2; }
[[ "$OLD_HOST" =~ ^[A-Za-z0-9._@:-]+$ ]] || { warn "invalid SSH target"; exit 2; }
for command in aws ssh uv; do command -v "$command" >/dev/null || { warn "$command is required"; exit 2; }; done
[[ -n "${DATABASE_URL:-}" ]] || { warn "export DATABASE_URL before running wizard"; exit 2; }
write_env ACTION "$ACTION"
write_env ALERT_PATH "$ALERT_PATH"
write_env CONTROL_BUCKET "$CONTROL_BUCKET"
write_env OLD_HOST "$OLD_HOST"

stage "Fence new delivery"
if [[ "$ACTION" == "cutover" ]]; then
  say "Shadow keeps source reads, Postgres state, and rendered payloads active without Slack posts."
  confirm "Set $ALERT_PATH to shadow in S3?" || exit 1
  set_control shadow
else
  warn "Rollback first disables selected new timer and stops its active service."
  confirm "Set $ALERT_PATH to disabled in S3?" || exit 1
  set_control disabled
fi
step "Wait at least 75 seconds for alerting-control.timer to apply this state."
pause "Press Enter after the control interval has elapsed."

stage "Inspect or archive durable output"
if [[ "$ACTION" == "cutover" ]]; then
  uv run --project alerting vllm-alerting-cutover export-shadow --path "$ALERT_PATH" --limit 10
  if [[ "$ALERT_PATH" == "fast_ci" ]]; then
    step "On $OLD_HOST, run /home/ubuntu/vllm-fast-ci-failure-alert/scripts/fast_ci_failure_alert.py --dry-run."
    step "Compare job IDs, names, durations, and links with shadow payloads above."
  else
    step "On $OLD_HOST, inspect latest output from /home/ubuntu/vllm-ci-report/tasks/vllm-ci-report.yaml."
    step "Compare build identity, failed jobs, lifecycle, attribution, and rendered report text."
  fi
  confirm "Do representative shadow results materially match current production?" || exit 1
else
  warn "This preserves pending live payloads as shadow records before old delivery resumes."
  confirm "Archive pending live $ALERT_PATH records?" || exit 1
  uv run --project alerting vllm-alerting-cutover archive-pending \
    --path "$ALERT_PATH" --confirm-path "$ALERT_PATH"
fi

stage "Fence or restore old producer"
if [[ "$ALERT_PATH" == "fast_ci" ]]; then
  if [[ "$ACTION" == "cutover" ]]; then
    warn "Only the old Fast CI alert timer and its active service will stop."
    confirm "Disable and mask old Fast CI timer and service on $OLD_HOST?" || exit 1
    ssh "$OLD_HOST" "sudo systemctl disable --now vllm-fast-ci-failure-alert.timer && sudo systemctl stop vllm-fast-ci-failure-alert.service && sudo systemctl mask vllm-fast-ci-failure-alert.timer vllm-fast-ci-failure-alert.service"
  else
    confirm "Unmask old Fast CI service and restore its timer on $OLD_HOST?" || exit 1
    ssh "$OLD_HOST" "sudo systemctl unmask vllm-fast-ci-failure-alert.service vllm-fast-ci-failure-alert.timer && sudo systemctl enable --now vllm-fast-ci-failure-alert.timer"
  fi
else
  warn "Full CI shares claude-cron with unrelated automations. Never stop shared service."
  step "SSH to $OLD_HOST and edit only /home/ubuntu/vllm-ci-report/tasks/vllm-ci-report.yaml."
  if [[ "$ACTION" == "cutover" ]]; then
    step "Disable and fence only Full CI results-report task; preserve every unrelated task."
    step "Confirm no active Full CI results-report invocation remains before continuing."
  else
    step "Restore only Full CI results-report task; preserve every unrelated task."
  fi
  confirm "Is only old Full CI results-report task now in requested state?" || exit 1
fi

stage "Activate or hold new path"
if [[ "$ACTION" == "cutover" ]]; then
  warn "Old producer must already be fenced before new Slack delivery becomes live."
  confirm "Set new $ALERT_PATH path live?" || exit 1
  set_control live
  step "Wait at least 75 seconds for selected new timer to enable."
else
  say "New $ALERT_PATH remains disabled. Postgres and S3 baselines were not rewound."
fi
pause "Press Enter after verifying requested control state in S3."

stage "Verify final state"
aws s3 cp "s3://${CONTROL_BUCKET}/control/${ALERT_PATH}.mode" -
if [[ "$ACTION" == "cutover" ]]; then
  step "Confirm old selected producer remains fenced."
  step "After next scheduled run, confirm new records use delivery_mode=live and only selected Slack path posts."
else
  step "Confirm new selected path remains disabled and old selected producer is scheduled."
  step "Do not delete or rewind Postgres comparisons, deduplication keys, or S3 checkpoints."
fi
confirm "Does final state satisfy these checks?" || exit 1

finish
